import { BUILDINGS } from './constants.js';

export const elements = [
  { room: 'K1', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'K2', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'K3', building: BUILDINGS.KAKENHUS, floor: 2},
   { room: 'K4', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'K101', building: BUILDINGS.KAKENHUS, floor: 1},
  { room: 'K102', building: BUILDINGS.KAKENHUS, floor: 1},
  { room: 'K103', building: BUILDINGS.KAKENHUS, floor: 1},
  { room: 'K104', building: BUILDINGS.KAKENHUS, floor: 1},
  { room: 'K105', building: BUILDINGS.KAKENHUS, floor: 1},
  { room: 'K106', building: BUILDINGS.KAKENHUS, floor: 1},
  { room: 'K2411', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K2415', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K21', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'K22', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'K24', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'K2414', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K2427', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K2429', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K25', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'K501', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K505', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2426', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K502', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K52', building: BUILDINGS.KAKENHUS, floor: 5},
  { room:'K2509', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2511', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K51', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2528', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2515', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2516', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2517', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2524', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2525', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2526', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2527', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2529', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K2332', building: BUILDINGS.KAKENHUS, floor: 3},
  { room: 'K5421', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K5420', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K42', building: BUILDINGS.KAKENHUS, floor: 4},
  { room: 'K4507', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K4504', building: BUILDINGS.KAKENHUS, floor: 5},
  { room: 'K23', building: BUILDINGS.KAKENHUS, floor: 2},
  { room: 'Fargeriet', building: BUILDINGS.KAKENHUS, floor: 1},
  {room: 'TP1', floor: 3, building: BUILDINGS.TAPPAN},
  {room: 'TP2', floor: 3, building: BUILDINGS.TAPPAN},
  {room: 'TP32', floor: 3, building: BUILDINGS.TAPPAN},
  {room: 'TP31', floor: 3, building: BUILDINGS.TAPPAN},
  {room: 'TP301', floor: 3, building: BUILDINGS.TAPPAN},
  {room: 'TP5002', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5003', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5004', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5015', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5016', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5020', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5021', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5022', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5023', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5024', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5032', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5034', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP5050', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TPm51', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TPm52', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TPm54', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TPm55', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP51', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP52', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP53', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP54', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP55', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP56', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP501', floor: 5, building: BUILDINGS.TAPPAN},
  {room: 'TP4003', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4004', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4005', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4006', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4008', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4009', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4018', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4027', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4028', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4029', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4030', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4032', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4033', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4034', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4035', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4040', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP4041', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP41', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP42', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP43', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP44', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP45', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP401', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP402', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP403', floor: 4, building: BUILDINGS.TAPPAN},
  {room: 'TP404', floor: 4, building: BUILDINGS.TAPPAN}
];

const roomData = {
    elements
};

export default roomData;